[project]
name = "ai-scientist-lit-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.2",
    "paper-qa>=5.0.10",
    "pip>=24.2",
    "pre-commit>=4.0.1",
]
